name: markin-ai-diplom
on:
  push:
    branches:
      - main
env:
  IMAGE_TAG: markinai/diplom_app
  RELEASE_NAME: myapp
  NAMESPACE: default

jobs:
  build-and-push:
    name: Build Docker image & push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract version from commit messages
        run: |
          VERSION=$(git log -1 --pretty=format:"%h")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}

